/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stocks_Crawler */

#ifndef _Included_stocks_Crawler
#define _Included_stocks_Crawler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stocks_Crawler
 * Method:    makeJSON
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_stocks_Crawler_makeJSON
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
